services:
  - name: cors-proxy                 # appears in the Render dash & URL
    type: web                        # incoming HTTP traffic
    runtime: node                    # uses Render’s Node LTS image
    branch: main                     # auto‑deploy on pushes to main
    plan: free                       # 512 MB RAM & 100 s request timeout
    buildCommand: npm ci             # faster, reproducible installs
    startCommand: node server.js     # server.js already honors $PORT
    healthCheckPath: /               # optional; proxy home page returns 200
    envVars:                         # ⇣ everything here becomes process.env
      - key: CORSANYWHERE_WHITELIST
        value: https://pl.escort.club
      - key: CORSANYWHERE_RATELIMIT
        value: "600 10 pl.escort.club"
      - key: NODE_ENV                # always good practice
        value: production